services:
  master-bdd:
    container_name: master-bdd
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: TOOR
      MARIADB_DATABASE: maalsi24
      MARIADB_USER: user
      MARIADB_PASSWORD: resu
    
  master-back:
    container_name: master-back
    image: senseo/masterbus:back
    restart: always
    depends_on: 
      - master-bdd
    ports:
      - 52000:52000
    environment:
      BDD_HOST: master-bdd
      BDD_PORT: 3306

  master-adminer:
    container_name: master-adminer
    image: adminer
    ports:
      - 8081:8080

  master-front:
    container_name: master-front
    image: senseo/masterbus:front
    ports:
      - 8080:80
